#!/usr/bin/env python3
"""Generate the caliper worksheet from dimensions.yaml.

Writes docs/calibration_report.md: one row per dimension that is not yet
measured, with the current estimate in millimeters, what exactly to put the
caliper on, and an empty column to write the measurement into. Run it again
after updating dimensions.yaml and the worksheet regenerates.

Usage:  python3 scripts/calibration_report.py
"""
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
DIMENSIONS = REPO / 'soma_description' / 'config' / 'dimensions.yaml'
REPORT = REPO / 'docs' / 'calibration_report.md'


def main() -> None:
    data = yaml.safe_load(DIMENSIONS.read_text())
    sections = {k: v for k, v in data.items()
                if isinstance(v, dict) and 'dimensions' in v}

    lines = [
        '# Calibration worksheet (v0.1)',
        '',
        'Generated by `scripts/calibration_report.py` from',
        '`soma_description/config/dimensions.yaml`. Do not edit by hand;',
        'write the measurements into the yaml (value, status: measured,',
        'date) and into the xacro, then regenerate. CI keeps both in sync.',
        '',
        'Angles and axis-to-axis lengths are center of screw to center of',
        'screw. Measure in mm with the caliper; the yaml stores meters.',
        '',
    ]

    total = pending = 0
    for name, sec in sections.items():
        rows = []
        for dim, entry in sec['dimensions'].items():
            total += 1
            if entry['status'] == 'measured':
                continue
            pending += 1
            mm = entry['value'] * 1000.0
            rows.append(f"| `{dim}` | {mm:.1f} | {entry['status']} | "
                        f"{entry['measure']} |  |")
        if not rows:
            continue
        lines += [f"## {name}  (`{sec['file']}`)", '',
                  '| dimension | estimate (mm) | status | put the caliper on | measured (mm) |',
                  '|---|---|---|---|---|', *rows, '']

    lines += [f'{pending} of {total} dimensions still need a measurement. '
              'v0.1 closes when this number is zero for the `arm` section '
              '(`design` entries close with the torso build).', '']

    REPORT.write_text('\n'.join(lines))
    print(f'{REPORT.relative_to(REPO)}: {pending} pending of {total}')


if __name__ == '__main__':
    main()
